export const buttonFuncs = {
  CPT: { primary: "test", secondary: "quit" },
  ENTER: { primary: "test", secondary: "" },
  "↑": { primary: "test", secondary: "" },
  "↓": { primary: "test", secondary: "" },
  "ON|OFF": { primary: "test", secondary: "" },
  "2ND": { primary: "test", secondary: "" },
  CF: { primary: "test", secondary: "" },
  NPV: { primary: "test", secondary: "" },
  IRR: { primary: "test", secondary: "" },
  "→": { primary: "delete", secondary: "" },
  N: { primary: "test", secondary: "" },
  "I/Y": { primary: "test", secondary: "" },
  PV: { primary: "test", secondary: "" },
  PMT: { primary: "test", secondary: "" },
  FV: { primary: "test", secondary: "" },
  "%": { primary: "test", secondary: "" },
  "√𝑥": { primary: "test", secondary: "" },
  "𝑥²": { primary: "test", secondary: "" },
  "1/𝑥": { primary: "test", secondary: "" },
  "÷": { primary: "chooseOperation", secondary: "" },
  INV: { primary: "test", secondary: "" },
  "(": { primary: "test", secondary: "" },
  ")": { primary: "test", secondary: "" },
  yᵡ: { primary: "test", secondary: "" },
  "×": { primary: "chooseOperation", secondary: "" },
  LN: { primary: "test", secondary: "" },
  7: { primary: "appendNumber", secondary: "" },
  8: { primary: "appendNumber", secondary: "" },
  9: { primary: "appendNumber", secondary: "" },
  "-": { primary: "chooseOperation", secondary: "" },
  "SET TO": { primary: "test", secondary: "" },
  4: { primary: "appendNumber", secondary: "" },
  5: { primary: "appendNumber", secondary: "" },
  6: { primary: "appendNumber", secondary: "" },
  "+": { primary: "chooseOperation", secondary: "" },
  RCL: { primary: "test", secondary: "" },
  1: { primary: "appendNumber", secondary: "" },
  2: { primary: "appendNumber", secondary: "" },
  3: { primary: "appendNumber", secondary: "" },
  "=": { primary: "compute", secondary: "" },
  "CE|C": { primary: "clear", secondary: "" },
  0: { primary: "appendNumber", secondary: "" },
  ".": { primary: "appendNumber", secondary: "" },
  "+|-": { primary: "chooseOperation", secondary: "" },
};

export const keyFuncs = {
  "~": "+|-",
  1: 1,
  2: 2,
  3: 3,
  4: 4,
  5: 5,
  6: 6,
  7: 7,
  8: 8,
  9: 9,
  0: 0,
  ".": ".",
  "-": "-",
  "+": "+",
  "/": "÷",
  "*": "×",
  "%": "%",
  "^": "yᵡ",
  "(": "(",
  ")": ")",
  "=": "=",
  Enter: "=",
  Escape: "CE|C",
};
